//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karetka
    {
        public int ID_karetki { get; set; }
        public string typ_numer { get; set; }
        public int ID_skladu { get; set; }
        public string wyposazenie { get; set; }
        public string uwagi { get; set; }
    }
}
