//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacjenci1
    {
        public long PESEL { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int nr_ubezpieczenia { get; set; }
        public string miejscowosc { get; set; }
        public string kod_pocztowy { get; set; }
        public string ulica { get; set; }
        public string opis { get; set; }
        public string uwagi { get; set; }
        public string lekarz { get; set; }
        public Nullable<long> ID_lekarz { get; set; }
        public System.DateTime data_przyjecia { get; set; }
        public System.DateTime data_wypisania { get; set; }
    
        public virtual Personel1 Personel1 { get; set; }
    }
}
