//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel1
    {
        public Personel1()
        {
            this.Pacjenci1 = new HashSet<Pacjenci1>();
        }
    
        public long ID_lekarz { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string stanowisko { get; set; }
        public string specjalizacja { get; set; }
    
        public virtual ICollection<Pacjenci1> Pacjenci1 { get; set; }
    }
}
